name: mordor_suit
description: ""
publish_to: 'none'
environment:
  sdk: '>=3.2.6 <4.0.0'

version: 1.0.7+9

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx:
  flutter_dotenv: ^5.1.0
  flutter_mobx:
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  connectivity_plus: ^4.0.1
  url_launcher: ^6.1.12
  go_router: ^13.1.0
  dio: ^5.2.1+1
  uuid: ^4.3.3
  shared_preferences: ^2.0.7
  get_it: ^7.6.0
  feedback: ^3.0.0
  talker_flutter: 3.2.0
  talker_dio_logger: 2.3.0
  permission_handler: ^11.3.0
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  dots_indicator: ^3.0.0
  flutter_svg: ^2.0.10+1
  sentry_flutter: ^7.16.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider:
  flutter_cache_manager: ^3.3.1
  auto_size_text: ^3.0.0
  appmetrica_plugin: ^1.4.0
  app_settings: ^5.1.1
  infinite_carousel: ^1.1.1
  flutter_carousel_widget:
  carousel_slider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  mobx_codegen:
  hive_generator:

flutter:
  uses-material-design: true

  assets:
    - lib/.env
    - assets/images/
    - assets/images/items/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
